import '../styles/globals.css';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="bg-green-500">{children}</body>
    </html>
  );
}